#!/usr/bin/env ansible-playbook
- name: Setup hypervisor
  hosts: hypervisors

  pre_tasks:
    - name: Hypervisor OS is Ubuntu (noble)
      assert:
        that:
          - ansible_facts.distribution == "Ubuntu"
          - ansible_facts.distribution_release == "noble"
        fail_msg: "This playbook only supports Ubuntu Noble (24.04)."
        success_msg: "Assertions passed, running playbook..."

  tasks:
    - debug:
        msg: '{{ root_disks }}'

    - name: Update apt package list
      apt:
        update_cache: True
      changed_when: False

    - name: Install Hypervisor packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - qemu-kvm
        - libvirt-daemon-system
        - libvirt-clients
        - bridge-utils
        - genisoimage

    - name: Install mDNS packages for .local resolution
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - libnss-mdns
        - avahi-daemon
        - avahi-utils

    - name: Update avahi-daemon.conf for only br0
      lineinfile:
        path: /etc/avahi/avahi-daemon.conf
        regexp: '^#?allow-interfaces=.*'
        line: 'allow-interfaces=br0'
        backrefs: yes
      notify: restart avahi-daemon

    - name: Disable and stop apparmor service
      systemd:
        name: apparmor
        state: stopped
        enabled: no

    - name: Update OS physical volume
      lvg:
        vg: ubuntu-vg
        pvs: "{{ root_disks | join(',') }}"
        pvresize: True
      when: root_disks | length > 0

    - name: Update OS logical vol
      lvol:
        vg: ubuntu-vg
        lv: ubuntu-lv
        size: 95%PVS
        resizefs: True

    - name: Create /data directory for VM storage
      file:
        path: /data
        state: directory
        mode: 0755
        owner: libvirt-qemu
        group: kvm

    - name: Add libvirt, libvirt-qemu, and libvirt-dnsmasq groups to ansible user
      user:
        name: "{{ ansible_user }}"
        groups: libvirt,libvirt-qemu,libvirt-dnsmasq
        append: yes
      when: ansible_user | length > 0

    - name: Grant passwordless sudo to ansible user
      copy:
        dest: "/etc/sudoers.d/{{ ansible_user }}"
        content: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
        mode: 0440
        owner: root
        group: root
      when: ansible_user | length > 0
 
    - name: Update /etc/default/grub for GPU pass through
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX='
        line: "GRUB_CMDLINE_LINUX=\"amd_iommu=on amd_iommu=pt mitigations=off apparmor=0 video=efifb:off pcie_acs_override=downstream,multifunction vfio-pci.ids={{ gpu_pci_ids | join(',') }} vfio-pci.disable_vga=1\""
      notify:
        - update grub
        - reboot system
      when:
        - gpu_pci_ids | length > 0
        - has_gpu == True

    - name: Blacklist GPU modules
      copy:
        dest: /etc/modprobe.d/no-gpu.conf
        content: |-
          # Blacklist Nvidia GPU modules
          blacklist nvidia
          blacklist nvidia_drm
          blacklist nvidia_uvm
          blacklist nvidia_modeset
          blacklist nvidiafb
          blacklist nouveau
          # Blacklist Intel Arc / Xe GPU modules
          blacklist xe
          blacklist i915
      notify:
        - update initramfs
        - reboot system
      when: has_gpu == True

    - name: Send over netplan for br0 setup
      copy:
        src: 50-cloud-init.yaml
        dest: /etc/netplan/50-cloud-init.yaml
        mode: 0600
        owner: root
        group: root
      notify: reboot system

    - name: Disable Unattended-Upgrade in apt.conf
      copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "0";

    - name: Disable unattended upgrades service and timers
      systemd:
        name: "{{ item }}"
        enabled: False
        state: stopped
      loop:
        - unattended-upgrades.service
        - apt-daily-upgrade.timer

  handlers:
    - name: restart avahi-daemon
      systemd:
        name: avahi-daemon
        state: restarted
        enabled: yes

    - name: update grub
      command: update-grub

    - name: update initramfs
      command: update-initramfs -u

    - name: reboot system
      command: reboot
      async: 1
      poll: 0
      ignore_errors: True
